name: woe-usb
version: &version v3.3.0
summary: WoeUSB is a tool to create Windows USB stick
description: |
    WoeUSB is a simple tool that enable you to create your own 
    usb stick windows installer from an iso image or a real DVD. 
    It is a fork of Congelli501's WinUSB.

confinement: strict
grade: stable
architectures:
  - build-on: amd64
  - build-on: i386

apps:
  woeusb:
    command: bin/woeusb
    plugs:
      - home
      - removable-media
      - raw-usb
      - optical-drive
      - mount-observe 
      - udisks2
  woeusbgui:
    command: desktop-launch $SNAP/bin/woeusbgui
    plugs:
      - x11
      - wayland 
      - desktop
      - desktop-legacy
      - home
      - removable-media
      - raw-usb
      - optical-drive
      - mount-observe 
      - udisks2

parts:
  desktop-gtk2:
  wxwidgets-3-0-gtk2:
  woeusb:
    source: https://github.com/slacka/WoeUSB.git
    source-tag: *version
    source-type: git
    plugin: autotools
    override-build: |
      autoreconf --force --install
      snapcraftctl build
    build-packages:
      - build-essential
      - dh-autoreconf
      - libwxgtk3.0-dev
    stage-packages:
      - dosfstools
      - gettext
      - grub2-common
      - grub-pc-bin
      - ntfs-3g
      - p7zip-full
      - parted
      - policykit-1
      - wget
      - libwxgtk3.0-0v5
      - overlay-scrollbar
      - overlay-scrollbar-gtk2
      - libatk-adaptor
      - libgail-common
      - libcanberra-gtk-module
